added exceptional handling in user
harisoyo/HBS pull request #17
Opened 2021-02-25 06:17 UTC by pulkitdhingraoyo

Code Reviewer Checklist:
- [ ] Tech Documentation : On Knowledge/ Google Doc
- [ ] Proper formatting, indentation, No spelling mistakes
- [ ] Meaningful Variable, Function, Class Names etc.
- [ ] Proper usage of access modifiers - private, public etc
- [ ] No Duplicate Code
- [ ] PR should be less than 10 files
- [ ] Classes should be less than 200 lines
- [ ] Functions should be less than 20 lines
- [ ] Code Documentation
- [ ] Test Cases
- [ ] Local Functions (Function Group) optimized for space, time & resources used
- [ ] No unnecessary and unused variables
- [ ] No unnecessary database calls in code (Cache usage if possible)
- [ ] Proper Error Handling in place
- [ ] Proper Logging (such a way that it is easier to find it on Kibana)

2021-02-25 07:16 UTC, harisoyo requested changes

2021-02-25 07:16 UTC, harisoyo commented on src/main/java/com/example/hbs/exception/ExceptionHandler.java
> +package com.example.hbs.exception;
@aryan-dua already did this

2021-02-25 07:16 UTC, harisoyo commented on src/main/java/com/example/hbs/exception/HbsException.java
> +package com.example.hbs.exception;
same as above

2021-02-25 07:16 UTC, harisoyo commented on src/main/java/com/example/hbs/service/UserService.java
> +        return userMapper.map(userRepository.save(user));
we should throw an exception if some required value is missing
like role, email etc.

2021-03-02 02:07 UTC, vivekkrs commented on src/main/java/com/example/hbs/exception/ExceptionHandler.java
> +public class ExceptionHandler {
name it to HbsExceptionHandler

2021-03-02 02:10 UTC, vivekkrs commented on src/main/java/com/example/hbs/service/UserService.java
> +        User user = userRepository.findById(id).orElse(null);
you can throw exception here only,
`User user = userRepository.findById(id).orElseThrow(() -> new HbsException())`

2021-03-02 02:11 UTC, vivekkrs commented on src/main/java/com/example/hbs/service/UserService.java
> +        if (userRequestDto.getUserName() == null) {
check for both null and empty string

2021-03-02 02:12 UTC, vivekkrs commented on src/main/java/com/example/hbs/service/UserService.java
> +        if (userRequestDto.getUserEmail() == null) {
similarly, for the rest

2021-03-02 02:15 UTC, vivekkrs commented on src/main/java/com/example/hbs/exception/ExceptionHandler.java
> +    }
only one kind kf exception??
what if you have other exception and with some different http status code
like in many cases we return UNPROCESSABLE_ENTITY

2021-03-02 02:16 UTC, vivekkrs commented on src/main/java/com/example/hbs/exception/HbsException.java
> +public class HbsException extends RuntimeException{
other exceptions should inherit from it.

2021-03-03 10:49 UTC, vivekkrs commented on src/main/java/com/example/hbs/exception/HbsExceptionHandler.java
> +    @org.springframework.web.bind.annotation.ExceptionHandler({HbsException.class})
`@ExceptionHandler`
and import the interface

2021-03-03 10:50 UTC, vivekkrs commented on src/main/java/com/example/hbs/service/UserService.java
> +        //Optional.ofNullable(user).orElseThrow(() -> new HbsException("No such user Id found"));
remove unused code

2021-03-03 10:50 UTC, vivekkrs commented on src/main/java/com/example/hbs/exception/HbsException.java
> +}
a new line at the end

2021-03-03 13:25 UTC, harisoyo approved these changes

2021-03-03 13:25 UTC, harisoyo commented on src/main/java/com/example/hbs/service/UserService.java
> +        if (userRequestDto.getUserRole() == null ) {
Objects.isNull

2021-03-04 04:06 UTC, merged