Changed logic of Booking_Service layer
harisoyo/HBS pull request #18
Opened 2021-02-26 13:15 UTC by aryan-dua

Code Reviewer Checklist:
- [ ] Tech Documentation : On Knowledge/ Google Doc
- [ ] Proper formatting, indentation, No spelling mistakes
- [ ] Meaningful Variable, Function, Class Names etc.
- [ ] Proper usage of access modifiers - private, public etc
- [ ] No Duplicate Code
- [ ] PR should be less than 10 files
- [ ] Classes should be less than 200 lines
- [ ] Functions should be less than 20 lines
- [ ] Code Documentation
- [ ] Test Cases
- [ ] Local Functions (Function Group) optimized for space, time & resources used
- [ ] No unnecessary and unused variables
- [ ] No unnecessary database calls in code (Cache usage if possible)
- [ ] Proper Error Handling in place
- [ ] Proper Logging (such a way that it is easier to find it on Kibana)

2021-02-26 15:13 UTC, harisoyo requested changes

2021-02-26 15:13 UTC, harisoyo commented on src/main/java/com/example/hbs/service/HotelService.java
> +            CheckIfUserIdIsCorrect(userId);
Remove capitalization from function name

2021-02-26 16:12 UTC, aryan-dua commented on src/main/java/com/example/hbs/service/HotelService.java
> +            CheckIfUserIdIsCorrect(userId);
Okay

2021-03-02 02:20 UTC, vivekkrs approved these changes

2021-03-02 07:35 UTC, harisoyo approved these changes

2021-03-02 07:36 UTC, merged